development: &default
  adapter: postgresql
  min_messages: warning
  database: public
  host: localhost
  encoding: utf8

test: &test
  <<: *default
  database: health_test

production:
  adapter: postgresql
  min_messages: warning
  database: production
  host: localhost
  encoding: utf8
